version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  test:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Setup Tests
          command: |
            pip install pip-tools
            pip-compile requirements/tests.in
            mv requirements/tests.txt requirements.txt
            echo $HOME
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: Run Tests
          command: |
            coverage run -m pytest
            coverage report
            coverage html
      - store_artifacts:
          path: htmlcov

workflows:
  main:
    jobs:
      - test
