version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  test:
    executor: python/default
    working_directory: .
    steps:
      - checkout
      - run:
          command: |
            ls
            pip install pip-tools
            pip-compile requirements/tests.in
            mv requirements/tests.txt requirements.txt
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: pytest
          name: Test

workflows:
  main:
    jobs:
      - test
