version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  coverage:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: Run tests with coverage
          environment:
            COVERAGE_RCFILE: .coveragerc
          command: |
            python -m coverage run -m pytest
            python -m coverage report
            python -m coverage html
      - store_artifacts:
          path: htmlcov
  build:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Setup
          command: pip install --user build
      - run:
          name: Build
          command: python -m build

workflows:
  main:     
    jobs:
      - python/test
      - coverage:
        branches:
          only:
          - master
      - build
