version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  test:
    executor: python/default
    steps:
      - checkout
      - run: pip install pip-tools
      - run: pip-compile requirements/tests.in
      - run: mv requirements/tests.txt requirements.txt
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: pytest
          name: Test

workflows:
  main:
    jobs:
      - test
